### ISSUE TITLE
Unknown file type

### ISSUE THREAD

**Issue by wabosh** [McKay42/devil-daggers-extractor#1]
I don't have any problems with the tool (It works like a charm). But i don't know what type the files in the dd-archive archives are.
I found some shader-files and some other plain-text files, but nothing more.
Did you find out how to edit or open them?

**Comment by McKay42** [comment]
The dd file also contains all textures and models. Textures are probably very simple raw 8 bit RGB values with a width + height header on top from what I can remember, haven't looked at it yet though. There are 2 type flags stored with every subfile header, they should indicate which file it is (shader, sound, texture, model etc.), or you can just guess based on the contents because there is no mapping of flags to file types yet.

The game doesn't calculate a checksum for the two packages, so you can directly modify e.g. one of the GLSL shaders in plaintext if you open the entire package with a hex/text editor, and it will load it (I have tried, it does work). Seems 100% moddable.
